-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 19:37:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OO_bones
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db697237100
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db697237100
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db697237100` DEFAULT CHARACTER SET latin1 ;
USE `db697237100` ;

-- -----------------------------------------------------
-- Table `db697237100`.`admin_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`admin_groups` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`admin_login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`admin_login_attempts` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(15) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `time` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`admin_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`admin_users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(15) NOT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `activation_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_time` INT(11) UNSIGNED NULL DEFAULT NULL,
  `remember_code` VARCHAR(40) NULL DEFAULT NULL,
  `created_on` INT(11) UNSIGNED NOT NULL,
  `last_login` INT(11) UNSIGNED NULL DEFAULT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`admin_users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`admin_users_groups` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `group_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`api_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`api_access` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(40) NOT NULL DEFAULT '',
  `controller` VARCHAR(50) NOT NULL DEFAULT '',
  `date_created` DATETIME NULL DEFAULT NULL,
  `date_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`api_keys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`api_keys` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `key` VARCHAR(40) NOT NULL,
  `level` INT(2) NOT NULL,
  `ignore_limits` TINYINT(1) NOT NULL DEFAULT '0',
  `is_private_key` TINYINT(1) NOT NULL DEFAULT '0',
  `ip_addresses` TEXT NULL DEFAULT NULL,
  `date_created` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`api_limits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`api_limits` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uri` VARCHAR(255) NOT NULL,
  `count` INT(10) NOT NULL,
  `hour_started` INT(11) NOT NULL,
  `api_key` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`api_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`api_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uri` VARCHAR(255) NOT NULL,
  `method` VARCHAR(6) NOT NULL,
  `params` TEXT NULL DEFAULT NULL,
  `api_key` VARCHAR(40) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `time` INT(11) NOT NULL,
  `rtime` FLOAT NULL DEFAULT NULL,
  `authorized` VARCHAR(1) NOT NULL,
  `response_code` SMALLINT(3) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`calendar` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `shop_id` INT(11) NULL DEFAULT NULL,
  `date_in` DATETIME NULL DEFAULT NULL,
  `date_out` DATETIME NULL DEFAULT NULL,
  `value` VARCHAR(45) NULL DEFAULT NULL,
  `backgroundColor` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `borderColor` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `last_update` DATETIME NULL DEFAULT NULL,
  `all_day` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db697237100`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db697237100`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`customers` (
  `customer_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(15) NOT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `activation_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_time` INT(11) UNSIGNED NULL DEFAULT NULL,
  `remember_code` VARCHAR(40) NULL DEFAULT NULL,
  `created_on` INT(11) UNSIGNED NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `company` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `observations` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 68061
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`customers_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`customers_color` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` VARCHAR(15) NOT NULL,
  `description` VARCHAR(30) NOT NULL,
  `last_update` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`employees` (
  `employee_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `activation_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_time` INT(11) UNSIGNED NULL DEFAULT NULL,
  `remember_code` VARCHAR(40) NULL DEFAULT NULL,
  `created_on` INT(11) UNSIGNED NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `company` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `observations` VARCHAR(2000) NULL DEFAULT NULL,
  `has_photo` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `path_photo` VARCHAR(300) NULL DEFAULT NULL,
  `salary` INT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 68060
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`groups` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`invoice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(11) NOT NULL,
  `active` TINYINT(4) NOT NULL,
  `on_hold` TINYINT(4) NOT NULL,
  `paid` TINYINT(4) NOT NULL,
  `created_time` DATETIME NOT NULL,
  `last_update` DATETIME NOT NULL,
  `comment` VARCHAR(500) NULL DEFAULT NULL,
  `pay_method` VARCHAR(45) NULL DEFAULT 'CASH',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 262
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db697237100`.`invoice_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`invoice_customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `invoice_id` INT(11) NOT NULL COMMENT '	',
  `customer_id` INT(11) NOT NULL,
  `last_update` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 253
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db697237100`.`invoice_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`invoice_product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `invoice_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `last_update` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 483
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db697237100`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`login_attempts` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(15) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `time` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `REF` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price_base` FLOAT NULL DEFAULT NULL,
  `price_sale` FLOAT NULL DEFAULT NULL,
  `active` TINYINT(4) NULL DEFAULT NULL,
  `provider_id` INT(11) NULL DEFAULT NULL,
  `provider_string` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `last_update` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10205
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db697237100`.`products_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`products_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(45) NOT NULL,
  `catagory_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db697237100`.`taxes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`taxes` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db697237100`.`todos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`todos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `active` TINYINT(4) NOT NULL,
  `date_start` DATETIME NULL DEFAULT NULL,
  `date_finish` DATETIME NULL DEFAULT NULL,
  `last_update` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db697237100`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(15) NOT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `activation_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_time` INT(11) UNSIGNED NULL DEFAULT NULL,
  `remember_code` VARCHAR(40) NULL DEFAULT NULL,
  `created_on` INT(11) UNSIGNED NOT NULL,
  `last_login` INT(11) UNSIGNED NULL DEFAULT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `company` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db697237100`.`users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db697237100`.`users_groups` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `group_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
